In [1]:
# 이번엔 엑셀을 불러와서 데이터 프레임 만들기
# dataset 폴더의 excel_exam.xlsx 파일을 이용할 것
# pandas의 read_excel() 을 이용해서 불러온다.

import pandas as pd

In [2]:
df_exam=pd.read_excel('../datasets/day2_excel_exam.xlsx')
df_exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [4]:
sum(df_exam['english'])/20
# 영어점수의 평균

84.9

In [5]:
sum(df_exam['science'])/20
# 과학점수의 평균

59.45

In [13]:
# 여기서 전체 학생수를 잘 모르겠으면 len() 함수를 이용해보자
# len() 함수는 해당 리스트 값의 개수를 구하는 기능
df=pd.DataFrame({'a' : [1,2,2,3,4,4],
                'b' : [7,6,6,6,54,6],
                'c' : [2,1,9,7,4,7]})
df

   a   b  c
0  1   7  2
1  2   6  1
2  2   6  9
3  3   6  7
4  4  54  4
5  4   6  7

In [14]:
len(df['a'])

6

In [15]:
len(df)
# 둘 다 같은 값을 내뱉네. 어차피 갯수는 똑같다 이거겠지

6

In [16]:
sum(df_exam['english'])/len(df_exam)

84.9

In [17]:
sum(df_exam['science'])/len(df_exam)

59.45

In [18]:
# 만약 첫번째 행에 변수 명이 첫번째 행에 없고 바로 데이터가 입력되어 있으면?
# 첫번째 행의 데이터가 변수명으로 지정되면서 데이터가 유실되는 문제 발생
df_excel_novar=pd.read_excel('../datasets/day2_excel_exam_novar.xlsx')
df_excel_novar

   1  1.1  50  98  50.1
0  2    1  60  97    60
1  3    2  25  80    65
2  4    2  50  89    98
3  5    3  20  98    15
4  6    3  50  98    45
5  7    4  46  98    65
6  8    4  48  87    12

In [19]:
df_excel_novar=pd.read_excel('../datasets/day2_excel_exam_novar.xlsx', header=None)
df_excel_novar
# 헤더를 none으로 입력하면 첫번째 행을 변수명이 아닌 데이터로 인식해서 불러온다.
# 변수명은 0부터 시작하는 숫자로 자동지정

   0  1   2   3   4
0  1  1  50  98  50
1  2  1  60  97  60
2  3  2  25  80  65
3  4  2  50  89  98
4  5  3  20  98  15
5  6  3  50  98  45
6  7  4  46  98  65
7  8  4  48  87  12

In [23]:
# 엑셀 파일의 특정 시트를 불러오려면? 두번째 시트 (첫번째는 0 (기본값) )
df_excel_sheet2=pd.read_excel('../datasets/day2_excel_exam_sheet2.xlsx', sheet_name=1)
df_excel_sheet2

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32

In [24]:
# 시트 이름으로 해도 됨
df_excel_sheet2=pd.read_excel('../datasets/day2_excel_exam_sheet2.xlsx', sheet_name='Sheet2')
df_excel_sheet2

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32