In [1]:
import pandas as pd
exam=pd.read_csv('../../datasets/public/exam.csv')
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [2]:
# 오름차순으로 정렬하기
exam.sort_values('math') # math를 기준으로 오름차순 정렬

    id  nclass  math  english  science
8    9       3    20       98       15
4    5       2    25       80       65
3    4       1    30       98       58
2    3       1    45       86       78
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
0    1       1    50       98       50
9   10       3    50       98       45
5    6       2    50       89       98
15  16       4    58       98       65
1    2       1    60       97       60
10  11       3    65       65       65
16  17       5    65       68       98
14  15       4    75       56       78
19  20       5    78       83       58
6    7       2    80       90       45
17  18       5    80       78       90
18  19       5    89       68       87
7    8       2    90       78       25

In [3]:
exam.sort_values('math',ascending=False) # math를 기준으로 내림차순 정렬

    id  nclass  math  english  science
7    8       2    90       78       25
18  19       5    89       68       87
17  18       5    80       78       90
6    7       2    80       90       45
19  20       5    78       83       58
14  15       4    75       56       78
16  17       5    65       68       98
10  11       3    65       65       65
1    2       1    60       97       60
15  16       4    58       98       65
9   10       3    50       98       45
5    6       2    50       89       98
0    1       1    50       98       50
13  14       4    48       87       12
12  13       4    46       98       65
11  12       3    45       85       32
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
8    9       3    20       98       15

In [6]:
# 먼저오는 변수가 기준이 되고 ascending 없으면 오름차순이 기본값
exam.sort_values(['nclass','math'])

    id  nclass  math  english  science
3    4       1    30       98       58
2    3       1    45       86       78
0    1       1    50       98       50
1    2       1    60       97       60
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
11  12       3    45       85       32
9   10       3    50       98       45
10  11       3    65       65       65
12  13       4    46       98       65
13  14       4    48       87       12
15  16       4    58       98       65
14  15       4    75       56       78
16  17       5    65       68       98
19  20       5    78       83       58
17  18       5    80       78       90
18  19       5    89       68       87

In [13]:
# 여러개를 정렬기준으로 삼기도 가능
# nclass는 오름차순, science는 내림차순
exam.sort_values(['nclass','science'],ascending=[True,False])

    id  nclass  math  english  science
2    3       1    45       86       78
1    2       1    60       97       60
3    4       1    30       98       58
0    1       1    50       98       50
5    6       2    50       89       98
4    5       2    25       80       65
6    7       2    80       90       45
7    8       2    90       78       25
10  11       3    65       65       65
9   10       3    50       98       45
11  12       3    45       85       32
8    9       3    20       98       15
14  15       4    75       56       78
12  13       4    46       98       65
15  16       4    58       98       65
13  14       4    48       87       12
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [14]:
mpg=pd.read_csv('../../datasets/public/mpg.csv')

In [15]:
audi=mpg.query('manufacturer=="audi"')

In [17]:
audi.sort_values('hwy',ascending=False).head(5)

  manufacturer       model  displ  year  cyl       trans drv  cty  hwy fl category
2         audi          a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi          a4    2.0  2008    4    auto(av)   f   21   30  p  compact
0         audi          a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi          a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
9         audi  a4 quattro    2.0  2008    4  manual(m6)   4   20   28  p  compact