In [4]:
import pandas as pd
midwe=pd.read_csv('../../datasets/public/midwest.csv')
midwe

      PID     county state   area  ...  percadultpoverty  percelderlypoverty  inmetro  category
0     561      ADAMS    IL  0.052  ...         11.009776           12.443812        0       AAR
1     562  ALEXANDER    IL  0.014  ...         27.385647           25.228976        0       LHR
2     563       BOND    IL  0.022  ...         10.852090           12.697410        0       AAR
3     564      BOONE    IL  0.017  ...          5.536013            6.217047        1       ALU
4     565      BROWN    IL  0.018  ...         11.143211           19.200000        0       AAR
..    ...        ...   ...    ...  ...               ...                 ...      ...       ...
432  3048   WAUKESHA    WI  0.034  ...          2.590061            4.085479        1       HLU
433  3049    WAUPACA    WI  0.045  ...          6.953799           10.338641        0       AAR
434  3050   WAUSHARA    WI  0.037  ...         11.695784           11.804558        0       AAR
435  3051  WINNEBAGO    WI  0.035  ...          8.660587            6.661094        1       HAU
436  3052       WOOD    WI  0.048  ...          7.375656            7.882918        0       AAR

[437 rows x 28 columns]

In [5]:
df=midwe.head()
df

   PID     county state   area  poptotal  ...  percchildbelowpovert  percadultpoverty  percelderlypoverty  inmetro  category
0  561      ADAMS    IL  0.052     66090  ...             18.011717         11.009776           12.443812        0       AAR
1  562  ALEXANDER    IL  0.014     10626  ...             45.826514         27.385647           25.228976        0       LHR
2  563       BOND    IL  0.022     14991  ...             14.036061         10.852090           12.697410        0       AAR
3  564      BOONE    IL  0.017     30806  ...             11.179536          5.536013            6.217047        1       ALU
4  565      BROWN    IL  0.018      5836  ...             13.022889         11.143211           19.200000        0       AAR

[5 rows x 28 columns]

In [7]:
df.query('county=="ADAMS"|category=="AAR"')

   PID county state   area  poptotal  ...  percchildbelowpovert  percadultpoverty  percelderlypoverty  inmetro  category
0  561  ADAMS    IL  0.052     66090  ...             18.011717         11.009776           12.443812        0       AAR
2  563   BOND    IL  0.022     14991  ...             14.036061         10.852090           12.697410        0       AAR
4  565  BROWN    IL  0.018      5836  ...             13.022889         11.143211           19.200000        0       AAR

[3 rows x 28 columns]

In [8]:
df.query("county=='ADAMS'&category=='AAR'")

   PID county state   area  poptotal  ...  percchildbelowpovert  percadultpoverty  percelderlypoverty  inmetro  category
0  561  ADAMS    IL  0.052     66090  ...             18.011717         11.009776           12.443812        0       AAR

[1 rows x 28 columns]

In [9]:
var=13
df.query('percelderlypoverty>=@var')
# 위와 같이 @ 뒤에 변수를 넣어서 사용가능

   PID     county state   area  poptotal  ...  percchildbelowpovert  percadultpoverty  percelderlypoverty  inmetro  category
1  562  ALEXANDER    IL  0.014     10626  ...             45.826514         27.385647           25.228976        0       LHR
4  565      BROWN    IL  0.018      5836  ...             13.022889         11.143211           19.200000        0       AAR

[2 rows x 28 columns]

In [12]:
# 데이터프레임 출력 제한 설정해제
pd.set_option('display.max_rows',None) # 행 출력제한 해제 설정
pd.set_option('display.max_columns',None) # 열 출력제한 해제 설정

In [13]:
midwe

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,popother,percwhite,percblack,percamerindan,percasian,percother,popadults,perchsd,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,124,96.712059,2.575276,0.148283,0.376759,0.187623,43298,75.107395,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,9,66.384340,32.900433,0.178807,0.451722,0.084698,6724,59.726353,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,34,96.571276,2.861717,0.233473,0.106731,0.226803,9669,69.334988,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,1139,95.254171,0.412257,0.149322,0.486918,3.697332,19272,75.472188,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,6,90.198766,9.372858,0.239890,0.085675,0.102810,3979,68.861523,14.475999,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR
5,566,BUREAU,IL,0.050,35688,713.760000,35157,50,65,195,221,98.512105,0.140103,0.182134,0.546402,0.619256,23444,76.629415,18.904624,3.275891,35107,98.372002,10.399635,14.158819,8.179287,11.008586,0,AAR
6,567,CALHOUN,IL,0.017,5322,313.058824,5298,1,8,15,0,99.549042,0.018790,0.150319,0.281849,0.000000,3583,62.824449,11.917388,3.209601,5241,98.478016,15.149781,13.787761,12.932331,21.085271,0,LAR
7,568,CARROLL,IL,0.027,16805,622.407407,16519,111,30,61,84,98.298126,0.660518,0.178518,0.362987,0.499851,11323,75.951603,16.197121,3.055727,16455,97.917287,11.710726,17.225462,10.027037,9.525052,0,AAR
8,569,CASS,IL,0.024,13437,559.875000,13384,16,8,23,6,99.605567,0.119074,0.059537,0.171169,0.044653,8825,72.271955,14.107649,3.206799,13081,97.350599,13.875086,17.994784,11.914343,13.660180,0,AAR
9,570,CHAMPAIGN,IL,0.058,173025,2983.189660,146506,16559,331,8033,1596,84.673313,9.570293,0.191302,4.642682,0.922410,95971,87.499349,41.295808,17.757448,154934,89.544286,15.572437,14.132234,17.562728,8.105017,1,HAU
10,571,CHRISTIAN,IL,0.042,34418,819.476190,34176,82,51,89,20,99.296880,0.238247,0.148178,0.258586,0.058109,22945,73.074744,13.567226,3.089998,33788,98.169562,11.708299,16.320612,9.569700,11.490641,0,AAR
11,572,CLARK,IL,0.030,15921,530.700000,15842,10,26,36,7,99.503800,0.062810,0.163306,0.226116,0.043967,10734,71.334079,15.110863,2.776225,15615,98.078010,12.007685,15.321547,10.131775,12.595420,0,AAR
12,573,CLAY,IL,0.028,14460,516.428571,14403,4,17,29,7,99.605809,0.027663,0.117566,0.200553,0.048409,9647,65.564424,13.683010,2.788432,14248,98.533887,16.774284,20.582578,14.464114,17.670078,0,LAR
13,574,CLINTON,IL,0.029,33944,1170.482760,32688,1021,48,104,83,96.299788,3.007895,0.141409,0.306387,0.244520,21563,67.165979,15.387469,2.875296,32190,94.832666,10.223672,13.299402,9.253834,8.323176,1,LAU
14,575,COLES,IL,0.030,51644,1721.466670,50177,925,92,341,109,97.159399,1.791108,0.178143,0.660290,0.211060,29136,76.105162,25.175041,8.144563,45693,88.476880,16.748736,16.341941,18.792914,10.993608,0,AAR
15,576,COOK,IL,0.058,5105067,88018.396600,3204947,1317147,10289,188565,384119,62.779725,25.800778,0.201545,3.693683,7.524270,3291995,73.405822,28.018117,8.329964,5023523,98.402685,14.198303,22.293497,11.665542,10.825269,1,AAU
16,577,CRAWFORD,IL,0.026,19464,748.615385,19300,63,34,48,19,99.157419,0.323674,0.174681,0.246609,0.097616,13317,76.030637,16.985808,3.334084,19123,98.248048,10.537050,13.809825,8.870243,10.803387,0,AAR
17,578,CUMBERLAND,IL,0.020,10670,533.500000,10627,5,6,26,6,99.597001,0.046860,0.056232,0.243674,0.056232,6727,72.246172,14.597889,2.690650,10590,99.250234,12.049103,13.603185,9.822264,15.284626,0,AAR
18,579,DE KALB,IL,0.038,77932,2050.842110,72968,2069,123,1751,1021,93.630344,2.654879,0.157830,2.246831,1.310117,41817,83.879762,32.835928,11.150967,69127,88.701689,13.544635,8.678238,17.047419,6.453908,1,HAU
19,580,DE WITT,IL,0.023,16516,718.086957,16387,25,37,43,24,99.218939,0.151368,0.224025,0.260354,0.145314,10941,74.645828,16.195960,3.308656,16238,98.316784,10.315310,13.568426,7.955993,12.255345,0,AAR
20,581,DOUGLAS,IL,0.025,19464,778.560000,19280,16,19,41,108,99.054665,0.082203,0.097616,0.210645,0.554871,12550,74.031873,16.868526,3.840637,19140,98.335388,9.629049,13.293543,7.924795,8.714363,0,AAR
21,582,DU PAGE,IL,0.020,781666,39083.300000,714905,15462,962,39634,10703,91.459140,1.978083,0.123070,5.070452,1.369255,502321,88.576826,42.768867,11.963266,771641,98.717483,2.714734,2.945252,2.399064,3.838249,1,HLU
22,583,EDGAR,IL,0.036,19595,544.305556,19469,68,24,24,10,99.356979,0.347027,0.122480,0.122480,0.051033,13082,73.520868,16.839933,3.676808,19258,98.280174,16.003739,22.827628,14.480957,11.762014,0,AAR
23,584,EDWARDS,IL,0.014,7440,531.428571,7401,6,8,19,6,99.475807,0.080645,0.107527,0.255376,0.080645,5019,69.675234,16.935645,2.450687,7350,98.790323,12.204082,15.159868,10.950250,11.859528,0,AAR
24,585,EFFINGHAM,IL,0.028,31704,1132.285710,31523,12,45,95,29,99.429094,0.037850,0.141938,0.299647,0.091471,19477,74.955075,20.275196,3.783950,31229,98.501766,8.994845,11.599832,6.974466,10.517498,0,AAR
25,586,FAYETTE,IL,0.044,20893,474.840909,20148,599,40,35,71,96.434212,2.866989,0.191452,0.167520,0.339827,13894,68.792284,13.602994,2.986901,19452,93.102953,13.618137,16.627635,12.134146,13.435829,0,AAR
26,587,FORD,IL,0.030,14275,475.833333,14157,43,14,40,21,99.173380,0.301226,0.098074,0.280210,0.147110,9592,77.168474,17.827356,3.899083,13860,97.092820,9.264069,13.571228,7.325288,8.787402,0,AAR
27,588,FRANKLIN,IL,0.025,40319,1612.760000,40068,36,106,84,25,99.377465,0.089288,0.262903,0.208339,0.062006,27214,66.664217,14.705666,2.432571,39703,98.472184,20.764174,31.074742,19.313537,13.679486,0,LHR
28,589,FULTON,IL,0.052,38080,732.307692,37117,668,83,105,107,97.471113,1.754202,0.217962,0.275735,0.280987,25592,73.847296,15.532198,2.997030,36393,95.569853,15.494738,22.812225,13.996573,11.019603,0,AAR
29,590,GALLATIN,IL,0.019,6909,363.631579,6842,42,10,11,4,99.030250,0.607903,0.144739,0.159213,0.057896,4680,58.418803,11.367521,2.692308,6737,97.510494,21.433873,29.724656,20.005596,16.230032,0,LHR
30,591,GREENE,IL,0.033,15317,464.151515,15231,14,50,17,5,99.438532,0.091402,0.326435,0.110988,0.032643,10031,69.045958,13.049546,2.711594,15096,98.557159,15.533916,20.030083,13.444049,14.943182,0,AAR
31,592,GRUNDY,IL,0.026,32337,1243.730770,31864,21,45,113,294,98.537279,0.064941,0.139159,0.349445,0.909175,20541,78.964023,18.377878,3.938465,31979,98.892909,6.616842,6.930472,5.327339,10.462008,1,ALU
32,593,HAMILTON,IL,0.025,8499,339.960000,8462,3,11,21,2,99.564655,0.035298,0.129427,0.247088,0.023532,5859,59.993173,14.046766,2.611367,8383,98.635133,19.849696,21.923269,17.050133,23.141967,0,LHR
33,594,HANCOCK,IL,0.047,21373,454.744681,21272,26,25,37,13,99.527441,0.121649,0.116970,0.173116,0.060824,14322,77.538053,20.660522,3.861193,20943,97.988116,11.784367,14.620207,9.829460,12.915205,0,AAR
34,595,HARDIN,IL,0.009,5189,576.555556,5062,85,16,13,13,97.552515,1.638081,0.308345,0.250530,0.250530,3492,59.736541,14.318442,2.605956,4954,95.471189,26.746064,35.141700,25.174284,21.196130,0,LHR
35,596,HENDERSON,IL,0.023,8096,352.000000,8037,8,29,10,12,99.271245,0.098814,0.358202,0.123518,0.148221,5467,73.349186,13.773550,2.176697,8030,99.184783,12.938979,15.608075,10.282353,16.295026,0,AAR
36,597,HENRY,IL,0.051,51159,1003.117650,49969,657,63,128,342,97.673919,1.284232,0.123145,0.250200,0.668504,33423,77.195345,18.723633,4.221644,50472,98.657128,10.479078,15.177263,8.635263,9.011540,1,AAU
37,598,IROQUOIS,IL,0.067,30787,459.507463,30154,164,43,69,357,97.943937,0.532692,0.139669,0.224121,1.159580,20578,73.437652,15.166683,3.226747,30189,98.057622,9.198715,11.676272,7.959263,9.100280,0,AAR
38,599,JACKSON,IL,0.036,61067,1696.305560,51991,6342,109,2178,447,85.137636,10.385314,0.178492,3.566574,0.731983,32172,78.767251,36.643665,14.089892,54230,88.804100,28.371750,26.392211,32.458483,13.815301,0,AHR
39,600,JASPER,IL,0.029,10609,365.827586,10574,1,11,17,6,99.670091,0.009426,0.103686,0.160241,0.056556,6835,69.700073,15.025604,2.765179,10511,99.076256,13.100561,17.437961,10.007610,14.562252,0,AAR
40,601,JEFFERSON,IL,0.033,37020,1121.818180,34856,1924,56,129,55,94.154511,5.197191,0.151270,0.348460,0.148568,24023,69.903842,18.369895,3.679807,36495,98.581848,16.056994,21.113499,13.635887,15.631524,0,AAR
41,602,JERSEY,IL,0.023,20539,893.000000,20346,96,43,32,22,99.060324,0.467403,0.209358,0.155801,0.107113,12847,71.915622,14.758309,3.136919,19611,95.481766,9.744531,11.825573,8.834321,9.299720,1,AAU
42,603,JO DAVIESS,IL,0.035,21821,623.457143,21732,14,20,29,26,99.592136,0.064158,0.091655,0.132900,0.119151,14409,74.092581,16.413353,3.428413,21610,99.033042,8.287830,9.291645,6.283983,11.839324,0,AAR
43,604,JOHNSON,IL,0.020,11347,567.350000,10230,1046,26,14,31,90.155988,9.218296,0.229135,0.123381,0.273200,7922,66.170159,14.352436,3.433476,9180,80.902441,15.555556,18.535060,12.266501,19.877532,0,LAR
44,605,KANE,IL,0.029,317471,10947.275900,269675,19006,620,4474,23696,84.944767,5.986689,0.195293,1.409263,7.463989,191807,77.719270,27.593883,7.013300,310740,97.879806,6.846560,9.590403,5.551679,6.313803,1,ALU
45,606,KANKAKEE,IL,0.039,96255,2468.076920,80194,14399,150,644,868,83.314114,14.959223,0.155836,0.669056,0.901771,59821,73.086374,17.640962,3.990238,92594,96.196561,13.296758,19.598328,10.888062,10.247965,1,AAU
46,607,KENDALL,IL,0.018,39413,2189.611110,38019,210,73,224,887,96.463096,0.532819,0.185218,0.568340,2.250526,24175,83.677353,24.889349,5.253361,39199,99.457032,3.385290,4.420172,2.355049,5.878511,1,HLU
47,608,KNOX,IL,0.042,56393,1342.690480,52413,2860,85,320,715,92.942386,5.071551,0.150728,0.567446,1.267888,37723,76.566021,19.343636,4.212284,53106,94.171262,13.868489,19.673376,12.883174,9.738717,0,AAR
48,609,LAKE,IL,0.028,516418,18443.500000,450666,34771,1198,12588,17195,87.267679,6.733112,0.231983,2.437560,3.329667,318475,84.726902,37.834053,11.464008,495312,95.913001,5.159778,6.767125,4.191939,6.164430,1,HLU
49,610,LA SALLE,IL,0.068,106913,1572.250000,103805,1153,206,523,1226,97.092963,1.078447,0.192680,0.489183,1.146727,70357,73.127052,16.899527,3.438180,104473,97.717771,11.101433,15.241787,9.212097,10.697147,0,AAR
50,611,LAWRENCE,IL,0.022,15972,726.000000,15759,151,31,21,10,98.666416,0.945404,0.194090,0.131480,0.062610,10950,69.232877,14.538813,1.945205,15347,96.086902,19.847527,31.112873,16.759706,14.883216,0,AHR
51,612,LEE,IL,0.043,34392,799.813953,32530,1222,84,181,375,94.585950,3.553152,0.244243,0.526285,1.090370,22661,76.280835,18.476678,4.042187,32162,93.515934,8.824078,10.537883,7.715425,9.526875,0,AAR
52,613,LIVINGSTON,IL,0.062,39301,633.887097,36551,2115,62,131,442,93.002723,5.381542,0.157757,0.333325,1.124653,26084,74.145070,14.503144,2.948167,35431,90.152922,9.325167,13.701159,8.020050,6.770407,0,AAR
53,614,LOGAN,IL,0.036,30798,855.500000,29223,1291,37,143,104,94.886032,4.191831,0.120138,0.464316,0.337684,20324,75.900413,17.949223,3.798465,28104,91.252679,10.781383,12.825846,9.964791,10.361363,0,AAR
54,615,MCDONOUGH,IL,0.034,35244,1036.588240,32992,1254,65,802,131,93.610260,3.558052,0.184429,2.275565,0.371694,18784,80.302385,27.928024,10.359881,28821,81.775621,19.052080,16.009317,22.403382,12.884384,0,HHR
55,616,MCHENRY,IL,0.036,183241,5090.027780,178895,310,299,1293,2444,97.628260,0.169176,0.163173,0.705628,1.333763,114721,84.507632,28.054149,6.417308,181636,99.124104,3.491599,4.069647,2.870246,5.064473,1,HLU
56,617,MCLEAN,IL,0.068,129180,1899.705880,121057,5563,203,1624,733,93.711875,4.306394,0.157145,1.257161,0.567425,72957,84.671793,33.818551,9.003934,117663,91.084533,11.875441,10.010509,13.715404,7.266603,1,HAU
57,618,MACON,IL,0.035,117206,3348.742860,102197,14135,157,506,211,87.194342,12.059963,0.133952,0.431719,0.180025,76297,76.211384,19.861856,4.984469,114042,97.300479,12.741797,19.257479,10.909584,8.984869,1,AAU
58,619,MACOUPIN,IL,0.050,47679,953.580000,47077,379,94,88,41,98.737390,0.794899,0.197152,0.184568,0.085992,31217,72.819297,14.008393,3.254637,46387,97.290212,13.212754,18.598894,10.817108,12.460907,0,AAR
59,620,MADISON,IL,0.045,249238,5538.622220,230217,16136,683,1420,782,92.368339,6.474133,0.274035,0.569737,0.313756,161517,75.814311,19.699474,4.949324,245370,98.448070,11.338795,16.670919,9.903051,8.291811,1,AAU
60,621,MARION,IL,0.035,41561,1187.457140,39647,1519,106,232,57,95.394721,3.654869,0.255047,0.558216,0.137148,27077,70.125937,16.449385,3.312775,40800,98.168956,16.367647,22.349310,13.928571,14.722483,0,AAR
61,622,MARSHALL,IL,0.023,12846,558.521739,12752,17,30,28,19,99.268255,0.132337,0.233536,0.217967,0.147906,8600,77.779070,17.534884,2.569767,12563,97.796980,9.384701,11.471793,7.503075,11.330561,0,AAR
62,623,MASON,IL,0.033,16269,493.000000,16180,8,27,38,16,99.452947,0.049173,0.165960,0.233573,0.098347,10729,72.578992,13.505453,2.898686,16025,98.500215,15.507020,24.113135,12.840096,11.603801,0,AAR
63,624,MASSAC,IL,0.014,14752,1053.714290,13804,870,37,31,10,93.573753,5.897505,0.250813,0.210141,0.067787,10068,65.305920,14.034565,2.930075,14348,97.261388,16.741009,22.980825,14.968237,14.328358,0,LAR
64,625,MENARD,IL,0.018,11164,620.222222,11101,9,29,14,11,99.435686,0.080616,0.259764,0.125403,0.098531,7390,77.307172,18.511502,3.518268,10964,98.208527,9.558555,12.450331,7.891637,10.144927,1,AAU
65,626,MERCER,IL,0.033,17290,523.939394,17155,30,33,35,37,99.219202,0.173511,0.190862,0.202429,0.213997,11357,77.353174,16.474421,3.117020,17006,98.357432,10.131718,11.466373,9.010870,11.433812,0,AAR
66,627,MONROE,IL,0.023,22422,974.869565,22262,13,53,57,37,99.286415,0.057979,0.236375,0.254215,0.165017,14613,75.863957,19.920619,3.318963,22071,98.434573,4.811744,4.774624,4.211979,6.836925,1,ALU
67,628,MONTGOMERY,IL,0.041,30728,749.463415,29956,559,49,66,98,97.487633,1.819188,0.159464,0.214788,0.318927,20386,72.191700,11.723732,2.526244,29003,94.386228,14.029583,17.795845,12.291226,13.470008,0,AAR
68,629,MORGAN,IL,0.033,36397,1102.939390,34561,1510,48,130,148,94.955628,4.148694,0.131879,0.357172,0.406627,23605,75.903410,20.724423,5.659818,33746,92.716433,11.195401,12.329090,10.141856,12.618389,0,AAR
69,630,MOULTRIE,IL,0.021,13930,663.333333,13884,8,22,13,3,99.669777,0.057430,0.157933,0.093324,0.021536,9282,70.286576,15.718595,2.995044,13356,95.879397,11.343217,15.266963,9.102693,11.856585,0,AAR
70,631,OGLE,IL,0.045,45957,1021.266670,44895,66,87,136,773,97.689144,0.143613,0.189307,0.295929,1.682007,29575,77.602705,18.779374,3.472527,45229,98.415910,7.245351,8.546185,6.261317,8.287084,1,ALU
71,632,PEORIA,IL,0.038,182827,4811.236840,154298,24892,312,2225,1100,84.395631,13.615057,0.170653,1.216997,0.601662,115963,77.932616,25.838414,6.590033,176647,96.619755,14.527844,21.871177,12.427585,10.318043,1,AAU
72,633,PERRY,IL,0.026,21412,823.538462,20901,399,26,63,23,97.613488,1.863441,0.121427,0.294228,0.107416,13921,67.839954,13.562244,2.205301,21090,98.496170,15.836889,20.859671,13.347590,15.866051,0,LAR
73,634,PIATT,IL,0.025,15548,621.920000,15508,8,16,11,5,99.742732,0.051454,0.102907,0.070749,0.032158,10458,82.950851,22.011857,5.192197,15315,98.501415,6.131244,7.067669,4.612260,9.167794,0,HLR
74,635,PIKE,IL,0.049,17577,358.714286,17499,8,24,32,14,99.556238,0.045514,0.136542,0.182056,0.079650,11820,69.856176,12.174281,2.309645,17365,98.793878,17.932623,23.332559,15.083477,18.277359,0,AHR
75,636,POPE,IL,0.022,4373,198.772727,4072,266,15,6,14,93.116853,6.082781,0.343014,0.137206,0.320146,2821,65.154201,14.250266,2.481390,4160,95.129202,25.168269,36.472946,24.414869,15.361139,0,LHR
76,637,PULASKI,IL,0.011,7523,683.909091,5032,2466,8,7,10,66.888210,32.779476,0.106341,0.093048,0.132926,4816,59.779900,14.368771,2.200997,7441,98.910009,30.184115,40.037418,23.867741,31.161972,0,LHR
77,638,PUTNAM,IL,0.010,5730,573.000000,5616,9,7,7,91,98.010471,0.157068,0.122164,0.122164,1.588133,3783,75.812847,16.521279,3.436426,5722,99.860384,7.549808,10.478062,6.227348,7.155172,0,AAR
78,639,RANDOLPH,IL,0.036,34583,960.638889,31532,2852,54,83,62,91.177746,8.246826,0.156146,0.240002,0.179279,22847,64.222874,12.741279,2.958813,30685,88.728566,11.002118,14.292509,8.995606,11.678487,0,LAR
79,640,RICHLAND,IL,0.022,16545,752.045455,16442,17,24,43,19,99.377455,0.102750,0.145059,0.259897,0.114838,10917,73.490886,21.507740,3.627370,16228,98.084013,13.975844,18.660061,12.068161,12.949430,0,AAR
80,641,ROCK ISLAND,IL,0.028,148723,5311.535710,133428,10488,354,1017,3436,89.715780,7.052036,0.238026,0.683822,2.310335,96715,77.374761,21.300729,4.497751,144662,97.269420,13.184527,19.375000,11.752093,9.057489,1,AAU
81,642,ST CLAIR,IL,0.040,262852,6571.300000,187866,71275,585,2007,1119,71.472159,27.116020,0.222559,0.763548,0.425715,162550,72.586896,21.184251,5.389111,257438,97.940286,17.431770,26.729188,14.265401,11.868633,1,AAU
82,643,SALINE,IL,0.022,26551,1206.863640,25452,931,66,40,62,95.860796,3.506459,0.248578,0.150653,0.233513,18020,63.224195,15.488346,3.634850,25545,96.211066,20.183989,26.699108,18.694407,16.846582,0,LHR
83,644,SANGAMON,IL,0.051,178386,3497.764710,162013,14364,290,1377,342,90.821589,8.052201,0.162569,0.771922,0.191719,117686,81.770984,28.988155,8.169196,175796,98.548092,9.888166,13.700858,8.212676,9.764429,1,HAU
84,645,SCHUYLER,IL,0.026,7498,288.384615,7479,2,9,6,2,99.746599,0.026674,0.120032,0.080021,0.026674,5090,69.410609,14.636542,2.750491,7365,98.226194,16.496945,21.913415,13.646113,16.780045,0,AAR
85,646,SCOTT,IL,0.015,5644,376.266667,5634,1,6,3,0,99.822821,0.017718,0.106308,0.053154,0.000000,3732,73.606645,13.076099,2.250804,5578,98.830617,11.527429,14.256480,9.370678,13.360656,0,AAR
86,647,SHELBY,IL,0.044,22261,505.931818,22190,14,27,27,3,99.681057,0.062890,0.121288,0.121288,0.013476,14745,72.722957,15.951170,3.784334,22010,98.872467,10.004543,12.091730,8.653418,10.629843,0,AAR
87,648,STARK,IL,0.017,6534,384.352941,6496,8,8,21,1,99.418427,0.122436,0.122436,0.321396,0.015305,4396,77.024568,16.878981,2.979982,6404,98.010407,12.460962,19.039146,10.447761,9.387483,0,AAR
88,649,STEPHENSON,IL,0.033,48052,1456.121210,44524,3081,58,304,85,92.657954,6.411804,0.120703,0.632648,0.176892,31555,76.691491,19.879575,3.882111,47225,98.278948,9.907888,13.503258,8.354173,9.505783,0,AAR
89,650,TAZEWELL,IL,0.039,123692,3171.589740,122639,186,221,432,214,99.148692,0.150374,0.178670,0.349255,0.173010,80310,78.594198,20.044826,3.921056,121970,98.607832,9.132574,12.893392,7.916417,7.288368,1,AAU
90,651,UNION,IL,0.024,17619,734.125000,17313,122,34,53,97,98.263238,0.692434,0.192973,0.300812,0.550542,12092,64.224281,17.879590,4.002646,16823,95.482150,18.159662,24.900200,14.679004,19.010096,0,LHR
91,652,VERMILION,IL,0.052,88257,1697.250000,78956,7841,165,507,788,89.461459,8.884281,0.186954,0.574459,0.892847,58087,72.751218,17.057173,4.061150,85119,96.444475,15.238666,22.540187,13.043382,11.409357,0,AAR
92,653,WABASH,IL,0.012,13111,1092.583330,12955,40,11,80,25,98.810159,0.305087,0.083899,0.610175,0.190680,8520,74.870892,24.730047,3.920188,12849,98.001678,12.942642,17.027588,11.527294,11.389961,0,AAR
93,654,WARREN,IL,0.033,19181,581.242424,18630,356,20,70,105,97.127366,1.856003,0.104270,0.364944,0.547417,12220,76.309329,20.458265,4.574468,18323,95.526823,14.233477,18.900966,12.832096,11.729916,0,AAR
94,655,WASHINGTON,IL,0.033,14965,453.484848,14856,46,31,26,6,99.271634,0.307384,0.207150,0.173739,0.040094,9906,65.727842,15.960024,2.442964,14620,97.694621,9.281806,9.816110,7.663601,12.377150,0,LAR
95,656,WAYNE,IL,0.042,17241,410.500000,17141,9,31,44,16,99.419987,0.052201,0.179804,0.255206,0.092802,11613,63.058641,15.680703,2.755533,17054,98.915376,14.395450,19.685594,11.616918,14.775213,0,LAR
96,657,WHITE,IL,0.029,16522,569.724138,16397,41,37,35,12,99.243433,0.248154,0.223944,0.211839,0.072630,11451,66.221291,15.928740,3.248625,16152,97.760562,19.056464,27.034053,16.487238,16.716196,0,LHR

In [18]:
# 설정 되돌리려면 새로운 커널을 사용하거나
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows')

pd.reset_option('all')

C:\Users\C\AppData\Local\Temp\ipykernel_23908\4014644199.py:5: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option('all')
C:\Users\C\AppData\Local\Temp\ipykernel_23908\4014644199.py:5: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')

In [19]:
mpg=pd.read_csv('../../datasets/public/mpg.csv')
mpg

    manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl category
0           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3           audi      a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p  compact
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..      ...
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p  midsize
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p  midsize
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p  midsize
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p  midsize
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p  midsize

[234 rows x 11 columns]

In [30]:
displ4=mpg.query('displ<=4')

In [31]:
displ4['hwy'].mean()

np.float64(25.96319018404908)

In [32]:
displ5=mpg.query('displ>=5')

In [33]:
displ5['hwy'].mean()

np.float64(18.07894736842105)

In [34]:
mpg.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [39]:
audi=mpg.query('manufacturer=="audi"')
audi

   manufacturer       model  displ  year  cyl       trans drv  cty  hwy fl category
0          audi          a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1          audi          a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2          audi          a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3          audi          a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4          audi          a4    2.8  1999    6    auto(l5)   f   16   26  p  compact
5          audi          a4    2.8  1999    6  manual(m5)   f   18   26  p  compact
6          audi          a4    3.1  2008    6    auto(av)   f   18   27  p  compact
7          audi  a4 quattro    1.8  1999    4  manual(m5)   4   18   26  p  compact
8          audi  a4 quattro    1.8  1999    4    auto(l5)   4   16   25  p  compact
9          audi  a4 quattro    2.0  2008    4  manual(m6)   4   20   28  p  compact
10         audi  a4 quattro    2.0  2008    4    auto(s6)   4   19   27  p  compact
11         audi  a4 quattro    2.8  1999    6    auto(l5)   4   15   25  p  compact
12         audi  a4 quattro    2.8  1999    6  manual(m5)   4   17   25  p  compact
13         audi  a4 quattro    3.1  2008    6    auto(s6)   4   17   25  p  compact
14         audi  a4 quattro    3.1  2008    6  manual(m6)   4   15   25  p  compact
15         audi  a6 quattro    2.8  1999    6    auto(l5)   4   15   24  p  midsize
16         audi  a6 quattro    3.1  2008    6    auto(s6)   4   17   25  p  midsize
17         audi  a6 quattro    4.2  2008    8    auto(s6)   4   16   23  p  midsize

In [40]:
toyota=mpg.query('manufacturer=="toyota"')
toyota

    manufacturer                   model  displ  year  cyl       trans drv  cty  hwy fl category
173       toyota             4runner 4wd    2.7  1999    4  manual(m5)   4   15   20  r      suv
174       toyota             4runner 4wd    2.7  1999    4    auto(l4)   4   16   20  r      suv
175       toyota             4runner 4wd    3.4  1999    6    auto(l4)   4   15   19  r      suv
176       toyota             4runner 4wd    3.4  1999    6  manual(m5)   4   15   17  r      suv
177       toyota             4runner 4wd    4.0  2008    6    auto(l5)   4   16   20  r      suv
178       toyota             4runner 4wd    4.7  2008    8    auto(l5)   4   14   17  r      suv
179       toyota                   camry    2.2  1999    4  manual(m5)   f   21   29  r  midsize
180       toyota                   camry    2.2  1999    4    auto(l4)   f   21   27  r  midsize
181       toyota                   camry    2.4  2008    4  manual(m5)   f   21   31  r  midsize
182       toyota                   camry    2.4  2008    4    auto(l5)   f   21   31  r  midsize
183       toyota                   camry    3.0  1999    6    auto(l4)   f   18   26  r  midsize
184       toyota                   camry    3.0  1999    6  manual(m5)   f   18   26  r  midsize
185       toyota                   camry    3.5  2008    6    auto(s6)   f   19   28  r  midsize
186       toyota            camry solara    2.2  1999    4    auto(l4)   f   21   27  r  compact
187       toyota            camry solara    2.2  1999    4  manual(m5)   f   21   29  r  compact
188       toyota            camry solara    2.4  2008    4  manual(m5)   f   21   31  r  compact
189       toyota            camry solara    2.4  2008    4    auto(s5)   f   22   31  r  compact
190       toyota            camry solara    3.0  1999    6    auto(l4)   f   18   26  r  compact
191       toyota            camry solara    3.0  1999    6  manual(m5)   f   18   26  r  compact
192       toyota            camry solara    3.3  2008    6    auto(s5)   f   18   27  r  compact
193       toyota                 corolla    1.8  1999    4    auto(l3)   f   24   30  r  compact
194       toyota                 corolla    1.8  1999    4    auto(l4)   f   24   33  r  compact
195       toyota                 corolla    1.8  1999    4  manual(m5)   f   26   35  r  compact
196       toyota                 corolla    1.8  2008    4  manual(m5)   f   28   37  r  compact
197       toyota                 corolla    1.8  2008    4    auto(l4)   f   26   35  r  compact
198       toyota  land cruiser wagon 4wd    4.7  1999    8    auto(l4)   4   11   15  r      suv
199       toyota  land cruiser wagon 4wd    5.7  2008    8    auto(s6)   4   13   18  r      suv
200       toyota       toyota tacoma 4wd    2.7  1999    4  manual(m5)   4   15   20  r   pickup
201       toyota       toyota tacoma 4wd    2.7  1999    4    auto(l4)   4   16   20  r   pickup
202       toyota       toyota tacoma 4wd    2.7  2008    4  manual(m5)   4   17   22  r   pickup
203       toyota       toyota tacoma 4wd    3.4  1999    6  manual(m5)   4   15   17  r   pickup
204       toyota       toyota tacoma 4wd    3.4  1999    6    auto(l4)   4   15   19  r   pickup
205       toyota       toyota tacoma 4wd    4.0  2008    6  manual(m6)   4   15   18  r   pickup
206       toyota       toyota tacoma 4wd    4.0  2008    6    auto(l5)   4   16   20  r   pickup

In [45]:
audi['cty'].mean()

np.float64(17.61111111111111)

In [46]:
toyota['cty'].mean()

np.float64(18.529411764705884)

In [51]:
# q3mean=mpg.query('manufacturer=="chevrolet"|manufacturer=="ford"|manufacturer=="honda"')
q3mean=mpg.query('manufacturer in ["chevrolet","ford","honda"]')
q3mean

    manufacturer               model  displ  year  cyl       trans drv  cty  hwy fl    category
18     chevrolet  c1500 suburban 2wd    5.3  2008    8    auto(l4)   r   14   20  r         suv
19     chevrolet  c1500 suburban 2wd    5.3  2008    8    auto(l4)   r   11   15  e         suv
20     chevrolet  c1500 suburban 2wd    5.3  2008    8    auto(l4)   r   14   20  r         suv
21     chevrolet  c1500 suburban 2wd    5.7  1999    8    auto(l4)   r   13   17  r         suv
22     chevrolet  c1500 suburban 2wd    6.0  2008    8    auto(l4)   r   12   17  r         suv
23     chevrolet            corvette    5.7  1999    8  manual(m6)   r   16   26  p     2seater
24     chevrolet            corvette    5.7  1999    8    auto(l4)   r   15   23  p     2seater
25     chevrolet            corvette    6.2  2008    8  manual(m6)   r   16   26  p     2seater
26     chevrolet            corvette    6.2  2008    8    auto(s6)   r   15   25  p     2seater
27     chevrolet            corvette    7.0  2008    8  manual(m6)   r   15   24  p     2seater
28     chevrolet     k1500 tahoe 4wd    5.3  2008    8    auto(l4)   4   14   19  r         suv
29     chevrolet     k1500 tahoe 4wd    5.3  2008    8    auto(l4)   4   11   14  e         suv
30     chevrolet     k1500 tahoe 4wd    5.7  1999    8    auto(l4)   4   11   15  r         suv
31     chevrolet     k1500 tahoe 4wd    6.5  1999    8    auto(l4)   4   14   17  d         suv
32     chevrolet              malibu    2.4  1999    4    auto(l4)   f   19   27  r     midsize
33     chevrolet              malibu    2.4  2008    4    auto(l4)   f   22   30  r     midsize
34     chevrolet              malibu    3.1  1999    6    auto(l4)   f   18   26  r     midsize
35     chevrolet              malibu    3.5  2008    6    auto(l4)   f   18   29  r     midsize
36     chevrolet              malibu    3.6  2008    6    auto(s6)   f   17   26  r     midsize
74          ford      expedition 2wd    4.6  1999    8    auto(l4)   r   11   17  r         suv
75          ford      expedition 2wd    5.4  1999    8    auto(l4)   r   11   17  r         suv
76          ford      expedition 2wd    5.4  2008    8    auto(l6)   r   12   18  r         suv
77          ford        explorer 4wd    4.0  1999    6    auto(l5)   4   14   17  r         suv
78          ford        explorer 4wd    4.0  1999    6  manual(m5)   4   15   19  r         suv
79          ford        explorer 4wd    4.0  1999    6    auto(l5)   4   14   17  r         suv
80          ford        explorer 4wd    4.0  2008    6    auto(l5)   4   13   19  r         suv
81          ford        explorer 4wd    4.6  2008    8    auto(l6)   4   13   19  r         suv
82          ford        explorer 4wd    5.0  1999    8    auto(l4)   4   13   17  r         suv
83          ford     f150 pickup 4wd    4.2  1999    6    auto(l4)   4   14   17  r      pickup
84          ford     f150 pickup 4wd    4.2  1999    6  manual(m5)   4   14   17  r      pickup
85          ford     f150 pickup 4wd    4.6  1999    8  manual(m5)   4   13   16  r      pickup
86          ford     f150 pickup 4wd    4.6  1999    8    auto(l4)   4   13   16  r      pickup
87          ford     f150 pickup 4wd    4.6  2008    8    auto(l4)   4   13   17  r      pickup
88          ford     f150 pickup 4wd    5.4  1999    8    auto(l4)   4   11   15  r      pickup
89          ford     f150 pickup 4wd    5.4  2008    8    auto(l4)   4   13   17  r      pickup
90          ford             mustang    3.8  1999    6  manual(m5)   r   18   26  r  subcompact
91          ford             mustang    3.8  1999    6    auto(l4)   r   18   25  r  subcompact
92          ford             mustang    4.0  2008    6  manual(m5)   r   17   26  r  subcompact
93          ford             mustang    4.0  2008    6    auto(l5)   r   16   24  r  subcompact
94          ford             mustang    4.6  1999    8    auto(l4)   r   15   21  r  subcompact
95          ford             mustang    4.6  1999    8  manual(m5)   r   15   22  r  subcompact
96          ford             mustang    4.6  2008    8  manual(m5)   r   15   23  r  subcompact
97          ford             mustang    4.6  2008    8    auto(l5)   r   15   22  r  subcompact
98          ford             mustang    5.4  2008    8  manual(m6)   r   14   20  p  subcompact
99         honda               civic    1.6  1999    4  manual(m5)   f   28   33  r  subcompact
100        honda               civic    1.6  1999    4    auto(l4)   f   24   32  r  subcompact
101        honda               civic    1.6  1999    4  manual(m5)   f   25   32  r  subcompact
102        honda               civic    1.6  1999    4  manual(m5)   f   23   29  p  subcompact
103        honda               civic    1.6  1999    4    auto(l4)   f   24   32  r  subcompact
104        honda               civic    1.8  2008    4  manual(m5)   f   26   34  r  subcompact
105        honda               civic    1.8  2008    4    auto(l5)   f   25   36  r  subcompact
106        honda               civic    1.8  2008    4    auto(l5)   f   24   36  c  subcompact
107        honda               civic    2.0  2008    4  manual(m6)   f   21   29  p  subcompact

In [49]:
q3mean['hwy'].mean()

np.float64(22.50943396226415)