In [1]:
import pandas as pd
exam=pd.read_csv('../../datasets/public/exam.csv')
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [2]:
# exam에서 nclass가 1인 것만 추출하기
# pd.query('추출하고자하는 카테고리==변수')
exam.query('nclass==1')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [3]:
exam.query('nclass==2')

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

In [4]:
exam.query('nclass!=1')

    id  nclass  math  english  science
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [6]:
exam.query('nclass>2')

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [7]:
# 초과, 미만, 이상, 이하 조건도 가능
exam.query('math>50')

    id  nclass  math  english  science
1    2       1    60       97       60
6    7       2    80       90       45
7    8       2    90       78       25
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [8]:
exam.query('math>=50')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
9   10       3    50       98       45
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [9]:
# 여러 조건을 충족하는 행 추출도 가능
exam.query('nclass>2&math>=50')

    id  nclass  math  english  science
9   10       3    50       98       45
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [17]:
exam.query('nclass==1&(english>80|science>=80)')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [18]:
# nclass가 1,3,5에 해당하면 추출
exam.query('nclass==[1,3,5]')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [19]:
# 추출한 행으로 데이터 만들기
nclass1=exam.query('nclass==1')
nclass1

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [32]:
nclass1['math'].mean()

np.float64(46.25)