In [1]:
import pandas as pd
exam=pd.read_csv('../../datasets/public/exam.csv')
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [5]:
# 일부 변수만 추출하기
# 데이터프레임 자료구조
exam[['nclass','english','math']]

    nclass  english  math
0        1       98    50
1        1       97    60
2        1       86    45
3        1       98    30
4        2       80    25
5        2       89    50
6        2       90    80
7        2       78    90
8        3       98    20
9        3       98    50
10       3       65    65
11       3       85    45
12       4       98    46
13       4       87    48
14       4       56    75
15       4       98    58
16       5       68    65
17       5       78    80
18       5       68    89
19       5       83    78

In [6]:
# [] 한개만 감싸면 시리즈 자료구조가 됨
# [[]] 두개 감싸면 데이터프레임 자료구조
exam['nclass']

0     1
1     1
2     1
3     1
4     2
5     2
6     2
7     2
8     3
9     3
10    3
11    3
12    4
13    4
14    4
15    4
16    5
17    5
18    5
19    5
Name: nclass, dtype: int64

In [7]:
exam[['nclass']]

    nclass
0        1
1        1
2        1
3        1
4        2
5        2
6        2
7        2
8        3
9        3
10       3
11       3
12       4
13       4
14       4
15       4
16       5
17       5
18       5
19       5

In [8]:
# 변수 제거하기
exam.drop(columns='math') # math 제거

    id  nclass  english  science
0    1       1       98       50
1    2       1       97       60
2    3       1       86       78
3    4       1       98       58
4    5       2       80       65
5    6       2       89       98
6    7       2       90       45
7    8       2       78       25
8    9       3       98       15
9   10       3       98       45
10  11       3       65       65
11  12       3       85       32
12  13       4       98       65
13  14       4       87       12
14  15       4       56       78
15  16       4       98       65
16  17       5       68       98
17  18       5       78       90
18  19       5       68       87
19  20       5       83       58

In [9]:
# 여러개 없애려면 배열형태
exam.drop(columns=['science','nclass'])

    id  math  english
0    1    50       98
1    2    60       97
2    3    45       86
3    4    30       98
4    5    25       80
5    6    50       89
6    7    80       90
7    8    90       78
8    9    20       98
9   10    50       98
10  11    65       65
11  12    45       85
12  13    46       98
13  14    48       87
14  15    75       56
15  16    58       98
16  17    65       68
17  18    80       78
18  19    89       68
19  20    78       83

In [10]:
examnew=pd.read_csv('../../datasets/public/exam.csv')

In [11]:
# nclass가 1인 행만 추출한 다음 그 중 english를 추출
exam.query('nclass==1')['english']

0    98
1    97
2    86
3    98
Name: english, dtype: int64

In [14]:
exam.query('math>=55')[['id','math']]

    id  math
1    2    60
6    7    80
7    8    90
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78

In [17]:
# 백슬래쉬로 코드 가독성 증가 가능
# 대신에 백슬래쉬 뒤에는 아무것도 붙으면 안됨
exam.query('math>=55')\
    [['id','math']]\
    .head(10)

    id  math
1    2    60
6    7    80
7    8    90
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78

In [18]:
mpg=pd.read_csv('../../datasets/public/mpg.csv')

In [19]:
mpg_cate_cty=mpg[['category','cty']]

In [20]:
mpg_cate_cty

    category  cty
0    compact   18
1    compact   21
2    compact   20
3    compact   21
4    compact   16
..       ...  ...
229  midsize   19
230  midsize   21
231  midsize   16
232  midsize   18
233  midsize   17

[234 rows x 2 columns]

In [25]:
mpg_compact=mpg.query('category =="compact"')

In [26]:
mpg_suv=mpg.query('category=="suv"')

In [27]:
mpg_compact['cty'].mean()

np.float64(20.127659574468087)

In [28]:
mpg_suv['cty'].mean()

np.float64(13.5)